### ISSUE TITLE
unable to import docker-compose file

### ISSUE THREAD

**Issue by stuartz** [dchqinc/dchq-io-issue-tracker#32]
when attempting to import a local docker-compose.yml file I get an error.  Firefox console error:

Error: JSON.parse: unexpected keyword at line 1 column 1 of the JSON data
H@https://www.dchq.io/js/all-index.min.js:215:128
a.importData@https://www.dchq.io/js/all-index.min.js:1503:429
dd.prototype.functionCall/<@https://www.dchq.io/js/all-index.min.js:385:464
dd.prototype.statements/<@https://www.dchq.io/js/all-index.min.js:379:482
Cb[b]</<.compile/</</c@https://www.dchq.io/js/all-index.min.js:403:186
nc/this.$get</r.prototype.$eval@https://www.dchq.io/js/all-index.min.js:317:389
nc/this.$get</r.prototype.$apply@https://www.dchq.io/js/all-index.min.js:318:165
Cb[b]</<.compile/</<@https://www.dchq.io/js/all-index.min.js:403:236
l.event.dispatch@https://www.dchq.io/js/all-index.min.js:125:396
l.event.add/g.handle@https://www.dchq.io/js/all-index.min.js:119:220

...return function(){a&&b.apply(c,arguments)}}()}}]}function Ba(a,b){if("__defineGe...

all-index.min.js (line 297)

**Comment by stuartz** [comment]
chrome error:
all-index.min.js:297 SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
    at Object.H [as fromJson] (https://www.dchq.io/js/all-index.min.js:215:133)
    at r.a.importData (https://www.dchq.io/js/all-index.min.js:1503:437)
    at https://www.dchq.io/js/all-index.min.js:385:466
    at https://www.dchq.io/js/all-index.min.js:379:482
    at c (https://www.dchq.io/js/all-index.min.js:403:186)
    at r.$eval (https://www.dchq.io/js/all-index.min.js:317:393)
    at r.$apply (https://www.dchq.io/js/all-index.min.js:318:170)
    at HTMLAnchorElement.<anonymous> (https://www.dchq.io/js/all-index.min.js:403:238)
    at HTMLAnchorElement.dispatch (https://www.dchq.io/js/all-index.min.js:125:448)

**Comment by intesar** [comment]
Only Chrome is the supported browser. Please try it on Chrome.
